# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NetWorkingDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  # Pods for NetWorkingDem 
  
  pod 'AFNetworking'
  pod 'Alamofire' 
  pod 'MJExtension' 
  pod 'SwiftyJSON' 
  pod 'SVProgressHUD', '~> 2.1.2'

end
